Pass max lifetime setting to DB connection pool
netology-group/event pull request #122
Opened 2020-09-01 11:46 UTC by feymartynov

2020-09-01 12:02 UTC, khodzha requested changes

2020-09-01 12:02 UTC, khodzha commented on src/db/mod.rs
> +        .max_lifetime(max_lifetime.map(Duration::from_secs));
if passed `max_lifetime` is `None` this will override r2d2 default max_lifetime of 30 minutes

2020-09-01 23:32 UTC, khodzha approved these changes

2020-09-02 06:58 UTC, manifest approved these changes

2020-09-02 06:59 UTC, merged