agent.ban method implementation
netology-group/event pull request #144
Opened 2020-10-21 12:32 UTC by khodzha

2020-10-21 12:40 UTC, feymartynov commented on src/app/endpoint/agent.rs
> +        let object = vec!["rooms", &room_id, "events", "message", "authors", &author];
Why only `message` but not all the events?

2020-10-21 12:40 UTC, feymartynov commented on src/app/endpoint/agent.rs
> +        )?;
What is this for?

2020-10-21 12:42 UTC, feymartynov commented on src/app/endpoint/agent.rs
> +    let value = if ban { "read_only_user" } else { "user" };
Is this hard coding to foxford's roles?

2020-10-21 14:13 UTC, manifest requested changes

2020-10-21 14:13 UTC, manifest commented on src/app/endpoint/agent.rs
> +        let object = vec!["rooms", &room_id, "events", "message", "authors", &author];
+1

2020-10-21 14:13 UTC, manifest commented on src/app/endpoint/agent.rs
> +        )?;
+1. It seems that we don't need to send anything, but a single `ok` response.

2020-10-22 14:30 UTC, manifest approved these changes

2020-11-03 04:23 UTC, feymartynov commented on src/db/agent.rs
> +            ON rban.room_id = agent.room_id AND rban.account_id = (agent.agent_id).account_id
Needs index on `agent_id.account_id` on `agents` table.

2020-11-03 04:23 UTC, feymartynov commented on src/app/endpoint/agent.rs
> +const BAN_DURATION_SECS: usize = 5 * 3600;
Shouldn't this be in config?

2020-11-03 04:23 UTC, feymartynov commented on src/app/endpoint/agent.rs
> +                "Failed to write user ban into redis, user = {}, ban = {}, reason = {}",
user -> account

2020-11-03 04:23 UTC, feymartynov commented on src/app/endpoint/authz/mod.rs
> +                }
Error handling?

2020-11-03 11:56 UTC, khodzha commented on src/db/agent.rs
> +            ON rban.room_id = agent.room_id AND rban.account_id = (agent.agent_id).account_id
there is an index on (room_id, account_id)
https://github.com/netology-group/event/blob/a321a18f17483e669f85fb1ecf79200916d63b81/migrations/20201030125521_add_account_room_ban.sql#L12

2020-11-03 11:57 UTC, khodzha commented on src/app/endpoint/agent.rs
> +const BAN_DURATION_SECS: usize = 5 * 3600;
not so sure, basically this is max webinar duration and is not expected to be configurable

2020-11-03 11:57 UTC, khodzha commented on docs/src/api/agent/ban.md
> +# agent.ban
addressed

2020-11-03 12:06 UTC, khodzha commented on src/app/endpoint/agent.rs
> +                "Failed to write user ban into redis, user = {}, ban = {}, reason = {}",
addressed

2020-11-03 12:16 UTC, khodzha commented on src/app/endpoint/agent.rs
> +struct MaybeBannedAgent {
i dislike `BannedAgent` because not all of them are banned

2020-11-03 12:30 UTC, khodzha commented on docs/src/api/agent/ban.md
> +The tenant authorizes the current _agent_ for `create` action on `["rooms", room_id, "claims", "role", "authors", current_account_id]`.
this is the only way for us to check whether an account is allowed to ban without introducing new authorization object

2020-11-05 11:27 UTC, alexkonst commented on docs/src/api/agent/update.md
> +**Label:** `agent.ban`.
`agent.update`

2020-11-16 08:37 UTC, merged