implemented RoomTime
netology-group/event pull request #162
Opened 2021-01-18 11:08 UTC by khodzha

2021-01-18 12:05 UTC, manifest approved these changes

2021-01-18 12:34 UTC, feymartynov requested changes

2021-01-18 12:34 UTC, feymartynov commented on src/app/endpoint/state.rs
> +        {
What if closing date is unbounded?

2021-01-18 12:34 UTC, feymartynov commented on src/app/operations/adjust_room.rs
> +                return Err(anyhow!(format!(
`bail!`

2021-01-18 12:34 UTC, feymartynov commented on src/db/room_time.rs
> +    }
I think it deserves unit tests for all combinations of old/new room time.

2021-01-21 19:06 UTC, feymartynov approved these changes

2021-01-21 19:32 UTC, merged